### ISSUE TITLE
Creating environment and protobuf error

### ISSUE THREAD

**Issue by andikatedja** [rudyhendrawn/scikit-learn-playground-app#12]
There is a typo in readme.md on creating environment, the fix is:
```
conda env create -f environment.yml
```
and then

When running `streamlit run app.py` I get the following error:
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
Fix that i have tried is downgrading the protobuf to version 3.20.1 by running this command:
```
pip install protobuf==3.20.1
```
My guess is when installing dependencies, conda auto install the latest version of protobuf, but it is not compatible with other dependencies. I also have tried to set all dependencies to the latest version in the environment.yml. No protobuf error, but there are some deprecated functions.

**Comment by rudyhendrawn** [comment]
Hi @andikatedja, I'm not sure if this problem has been solved or not. Are you installing it on your local machine?

**Comment by andikatedja** [comment]
The problem is solved. Yes, I am installing it on my local machine.
